version: '3.0'

expectations:
  population_size: 1000

actions:

  # this is for number of matches
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition 
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  ## this is to generate a date file for each month
  # generate_study_population_monthly:
  #   run: cohortextractor:latest generate_cohort 
  #     --study-definition study_definition_monthly 
  #     --index-date-range "2019-01-01 to today by month"
  #     --output-dir=output 
  #     --output-format=csv.gz 
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/input_*.csv.gz

  generate_study_population_measures:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_measures 
      --index-date-range "2019-01-01 to today by month" --skip-existing 
      --output-dir=output/measures 
      --output-format=csv.gz 
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz

## num_days added to study def measures, converted to integer,
## and added to pn_8wk_present variable in study defs

  generate_12wk_cohort:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_measures
      --output-format csv.gz
      --param num_days='84 days'
      --output-file output/input_12wk.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_12wk.csv.gz
  
  generate_8wk_cohort:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_measures 
      --output-format csv.gz
      --param num_days='56 days'
      --output-file output/input_8wk.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_8wk.csv.gz

  generate_6wk_cohort:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_measures
      --output-format csv.gz
      --param num_days='42 days'
      --output-file output/input_6wk.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_6wk.csv.gz

## do any changes need to be made here?  
  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_measures --skip-existing --output-dir=output/measures
    needs: [generate_study_population_measures]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv

  describe_del_code_freq:
    run: r:latest analysis/del_code_frequency.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        hist1: output/del_code_histogram.jpeg
        table1: output/table_del_codes.csv

  describe_del_code_freq_with_names:
    run: r:latest analysis/del_code_frequency_with_names.R
    needs: [generate_study_population, describe_del_code_freq]
    outputs:
      moderately_sensitive:
        table1: output/table_del_codes_with_names.csv

  describe_del_code_freq_with_names_reduced:
    run: r:latest analysis/del_code_frequency_with_names_reduced.R
    needs: [generate_study_population, describe_del_code_freq_with_names]
    outputs:
     moderately_sensitive:
        table1: output/table_del_codes_with_names_reduced.csv
        
  describe_pn_code_freq:
    run: r:latest analysis/pn_code_frequency.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        table1: output/table_pn_codes.csv

  describe_pn_code_freq_with_names:
    run: r:latest analysis/pn_code_frequency_with_names.R
    needs: [generate_study_population, describe_pn_code_freq]
    outputs:
      moderately_sensitive:
        table1: output/table_pn_codes_with_names.csv   

  describe_pn_code_freq_with_names_reduced:
    run: r:latest analysis/pn_code_frequency_with_names_reduced.R
    needs: [generate_study_population, describe_pn_code_freq_with_names]
    outputs:
     moderately_sensitive:
        table1: output/table_pn_codes_with_names_reduced.csv   

  describe_pn_rate_plots:
    run: r:latest analysis/pn_check_using_measures.R
    needs: [generate_study_population_measures, generate_measures]
    outputs:
      moderately_sensitive:
        plot1: output/monthly_pn_rate_measures8wkcode.jpeg

  describe_pn_rate_plots_by_age_cat:
    run: r:latest analysis/pn_check_using_measures_by_age_cat.R
    needs: [generate_study_population_measures, generate_measures]
    outputs:
      moderately_sensitive:
        plot2: output/monthly_pn_rate_measures8wkcode_by_age_cat.jpeg

  describe_pn_rate_plots_by_ethnicity:
    run: r:latest analysis/pn_check_using_measures_by_ethnicity.R
    needs: [generate_study_population_measures, generate_measures]
    outputs:
      moderately_sensitive:
        plot3: output/monthly_pn_rate_measures8wkcode_by_ethnicity.jpeg

  describe_pn_rate_plots_by_imd:
    run: r:latest analysis/pn_check_using_measures_by_imd.R
    needs: [generate_study_population_measures, generate_measures]
    outputs:
      moderately_sensitive:
        plot4: output/monthly_pn_rate_measures8wkcode_by_imd.jpeg
 
  describe_pn_rate_plots_by_practice:
    run: r:latest analysis/pn_check_using_measures_by_practice.R
    needs: [generate_study_population_measures, generate_measures]
    outputs:
      moderately_sensitive:
        plot5: output/monthly_pn_rate_measures8wkcode_by_practice.jpeg

  describe_baseline_table:
    run: r:latest analysis/baseline_table.R
    needs: [generate_study_population_measures, generate_measures]
    outputs:
      moderately_sensitive:
        table_overall: output/blt_overall.csv   
        table_before: output/blt_before.csv 
        table_after: output/blt_after.csv 
        table_overall_counts: output/overall_counts.csv
        table_counts_before: output/overall_counts_before.csv
        table_counts_after: output/overall_counts_after.csv 

