version: '3.0'

expectations:
  population_size: 1000
#change?

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output --output-format csv.gz 
      #index-date-range?
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz


#could generate different populations by month?
#index dates in study def can be overridden here
# so could be used for measures (what are we generating for these?)