version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition 
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  # generate_study_population_monthly:
  #   run: cohortextractor:latest generate_cohort 
  #     --study-definition study_definition_monthly 
  #     --index-date-range "2019-01-01 to today by month"
  #     --output-dir=output 
  #     --output-format=csv.gz 
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/input_*.csv.gz

  generate_study_population_measures:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_measures 
      --index-date-range "2019-01-01 to today by month" --skip-existing 
      --output-dir=output/measures 
      --output-format=csv.gz 
      --param num_days=84 
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz

###################################################################################################
#### generate cohorts of people with pn codes within 12, 8, 6 weeks of                         ####
#### date of last delivery code using 'num_days' param - these are used to generate measures   ####
###################################################################################################

  generate_12wk_cohort:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_measures
      --index-date-range "2019-01-01 to today by month" --skip-existing 
      --output-format csv.gz
      --param num_days=84
      --output-dir=output/pn12wk
    outputs:
      highly_sensitive:
        cohort: output/pn12wk/input_*.csv.gz
  
  generate_8wk_cohort:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_measures 
      --index-date-range "2019-01-01 to today by month" --skip-existing 
      --output-format csv.gz
      --param num_days=56
      --output-dir=output/pn8wk
    outputs:
      highly_sensitive:
        cohort: output/pn8wk/input_*.csv.gz

  generate_6wk_cohort:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_measures
      --index-date-range "2019-01-01 to today by month" --skip-existing 
      --output-format csv.gz
      --param num_days=42
      --output-dir=output/pn6wk
    outputs:
      highly_sensitive:
        cohort: output/pn6wk/input_*.csv.gz

  ############################################
  #### generate measures for each cohort  ####
  ############################################

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_measures --skip-existing --output-dir=output/measures --param num_days=84
    needs: [generate_study_population_measures]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv

  generate_measures_12wk:
    run: cohortextractor:latest generate_measures 
      --study-definition study_definition_measures 
      --skip-existing 
      --output-dir=output/pn12wk
      --param num_days=84
    needs: [generate_12wk_cohort]
    outputs:
      moderately_sensitive:
        measure_csv: output/pn12wk/measure_*.csv

  generate_measures_8wk:
    run: cohortextractor:latest generate_measures 
      --study-definition study_definition_measures 
      --skip-existing 
      --output-dir=output/pn8wk
      --param num_days=56
    needs: [generate_8wk_cohort]
    outputs:
      moderately_sensitive:
        measure_csv: output/pn8wk/measure*.csv

  generate_measures_6wk:
    run: cohortextractor:latest generate_measures 
      --study-definition study_definition_measures 
      --skip-existing 
      --output-dir=output/pn6wk
      --param num_days=42
    needs: [generate_6wk_cohort]
    outputs:
      moderately_sensitive:
        measure_csv: output/pn6wk/measure_*.csv

  #####################################################################
  #### generate tables with reduced/redacted frequencies and names ####
  #### of most frequent delivery and postnatal codes               ####
  #####################################################################

  describe_del_code_freq:
    run: r:latest analysis/del_code_frequency.R
    needs: [generate_8wk_cohort]
    outputs:
      moderately_sensitive:
        hist1: output/del_code_histogram_reviewed.jpeg
        table1: output/table_del_codes_reviewed.csv

  describe_del_code_freq_with_names:
    run: r:latest analysis/del_code_frequency_with_names.R
    needs: [generate_8wk_cohort, describe_del_code_freq]
    outputs:
      moderately_sensitive:
        table1: output/table_del_codes_reviewed_with_names.csv

  describe_del_code_freq_with_names_reduced:
    run: r:latest analysis/del_code_frequency_with_names_reduced.R
    needs: [generate_8wk_cohort, describe_del_code_freq_with_names]
    outputs:
     moderately_sensitive:
        table1: output/table_del_codes_reviewed_with_names_reduced.csv
        
  describe_pn_code_freq:
    run: r:latest analysis/pn_code_frequency.R
    needs: [generate_8wk_cohort]
    outputs:
      moderately_sensitive:
        hist2: output/pn_code_histogram_reviewed.jpeg
        table1: output/table_pn_codes_reviewed.csv

  describe_pn_code_freq_with_names:
     run: r:latest analysis/pn_code_frequency_with_names.R
     needs: [generate_8wk_cohort, describe_pn_code_freq]
     outputs:
       moderately_sensitive:
         table1: output/table_pn_codes_reviewed_with_names.csv   

  describe_pn_code_freq_with_names_reduced:
     run: r:latest analysis/pn_code_frequency_with_names_reduced.R
     needs: [generate_8wk_cohort, describe_pn_code_freq_with_names]
     outputs:
      moderately_sensitive:
         table1: output/table_pn_codes_reviewed_with_names_reduced.csv   

  # frequency of codes by unique patients
  describe_freq_by_unique_patients:
     run: r:latest analysis/del_code_and_pn_code_frequency_by_patient.R
     needs: [generate_8wk_cohort]
     outputs:
      moderately_sensitive:
         hist_del_code: output/del_code_histogram_reviewed_byPatient.jpeg
         hist_pn_code: output/pn_code_histogram_reviewed_byPatient.jpeg
         quantiles_del: output/del_code_quantiles_by_patients.csv
         quantiles_pn: output/pn_code_quantiles_by_patients.csv
         freq_del: output/table_del_codes_reviewed_overall.csv
         freq_pn: output/table_pn_codes_reviewed_overall.csv
         freq_del_namesR: output/table_del_codes_mergedR.csv
         freq_pn_namesR: output/table_pn_codes_mergedR.csv

  ## rate plots 
  # describe_pn_rate_plots:
  #   run: r:latest analysis/pn_check_using_measures_8wk.R
  #   needs: [generate_study_population_measures, generate_measures]
  #   outputs:
  #     moderately_sensitive:
  #       plot1: output/monthly_pn_rate_measures_overall.jpeg


######################################################
#### plots for rate of postnatal checks over time ####
#### overall (6/8/12 weeks and by category)       ####
######################################################
  
  describe_pn_rate_plots_8wk:
    run: r:latest analysis/pn_check_using_measures_8wk.R
    needs: [generate_8wk_cohort, generate_measures_8wk]
    outputs:
      moderately_sensitive:
        plot11: output/monthly_pn_rate_measures_8wk.jpeg
        table11: output/pn_check_combined_plot_8wk.csv

  # describe_pn_rate_plots_12wk:
  #   run: r:latest analysis/pn_check_using_measures_12wk.R
  #   needs: [generate_12wk_cohort, generate_measures_12wk]
  #   outputs:
  #     moderately_sensitive:
  #       plot12: output/monthly_pn_rate_measures_12wk.jpeg
  #       table12: output/pn_check_combined_plot_12wk.csv

  # describe_pn_rate_plots_6wk:
  #   run: r:latest analysis/pn_check_using_measures_6wk.R
  #   needs: [generate_6wk_cohort, generate_measures_6wk]
  #   outputs:
  #     moderately_sensitive:
  #       plot13: output/monthly_pn_rate_measures_6wk.jpeg  
  #       table13: output/pn_check_combined_plot_6wk.csv 

  describe_pn_rate_plots_combined:
    run: r:latest analysis/pn_check_using_measures_combined.R
    needs: [generate_6wk_cohort, generate_measures_6wk, generate_12wk_cohort, generate_measures_12wk, generate_8wk_cohort, generate_measures_8wk]
    outputs:
      moderately_sensitive:
        plot1b: output/monthly_pn_rate_measures_combined.jpeg     

  describe_pn_rate_plots_6wk:
    run: r:latest analysis/pn_check_using_measures_6wk.R
    needs: [generate_6wk_cohort, generate_measures_6wk]
    outputs:
      moderately_sensitive:
        plot1: output/monthly_pn_rate_measures_6wk.jpeg

  describe_pn_rate_plots_12wk:
    run: r:latest analysis/pn_check_using_measures_12wk.R
    needs: [generate_12wk_cohort, generate_measures_12wk]
    outputs:
      moderately_sensitive:
        plot1: output/monthly_pn_rate_measures_12wk.jpeg
        
  describe_pn_rate_plots_by_age_cat:
    run: r:latest analysis/pn_check_using_measures_by_age_cat_8wk.R
    needs: [generate_8wk_cohort, generate_measures_8wk]
    outputs:
      moderately_sensitive:
        plot2: output/monthly_pn_rate_measures8wkcode_by_age_cat_8wk.jpeg

  describe_pn_rate_plots_by_ethnicity:
    run: r:latest analysis/pn_check_using_measures_by_ethnicity_8wk.R
    needs: [generate_8wk_cohort, generate_measures_8wk]
    outputs:
      moderately_sensitive:
        plot3: output/monthly_pn_rate_measures8wkcode_by_ethnicity_8wk.jpeg

  describe_pn_rate_plots_by_imd:
    run: r:latest analysis/pn_check_using_measures_by_imd_8wk.R
    needs: [generate_8wk_cohort, generate_measures_8wk]
    outputs:
      moderately_sensitive:
        plot4: output/monthly_pn_rate_measures8wkcode_by_imd_8wk.jpeg
  
  #### rate plots by practice not currently used as data limited####
  
  # describe_pn_rate_plots_by_practice_8wk:
  #   run: r:latest analysis/pn_check_using_measures_by_practice_8wk.R
  #   needs: [generate_8wk_cohort, generate_measures_8wk]
  #   outputs:
  #     moderately_sensitive:
  #       plot5: output/monthly_pn_rate_measures8wkcode_by_practice_8wk.jpeg
  
  # describe_pn_rate_plots_by_practice_12wk:
  #   run: r:latest analysis/pn_check_using_measures_by_practice_12wk.R
  #   needs: [generate_12wk_cohort, generate_measures_12wk]
  #   outputs:
  #     moderately_sensitive:
  #       plot5: output/monthly_pn_rate_measures8wkcode_by_practice_12wk.jpeg
  
  # describe_pn_rate_plots_by_practice_6wk:
  #   run: r:latest analysis/pn_check_using_measures_by_practice_6wk.R
  #   needs: [generate_6wk_cohort, generate_measures_6wk]
  #   outputs:
  #      moderately_sensitive:
  #       plot5: output/monthly_pn_rate_measures8wkcode_by_practice_6wk.jpeg

  describe_pn_rate_plots_by_region:
    run: r:latest analysis/pn_check_using_measures_by_region_8wk.R
    needs: [generate_8wk_cohort, generate_measures_8wk]
    outputs:
      moderately_sensitive:
        plot6: output/monthly_pn_rate_measures8wkcode_by_region_8wk.jpeg

################################################
#### Generating baseline tables for cohorts ####
#### commented out as fails with dummy data ####
################################################

  describe_baseline_table_12wk_cohort:
    run: r:latest analysis/baseline_table_12wk.R
    needs: [generate_12wk_cohort]
    outputs:
      moderately_sensitive:
        table_overall: output/blt_overall_12wk.csv   
        table_before: output/blt_before_12wk.csv 
        table_after: output/blt_after_12wk.csv 
        table_overall_counts: output/overall_counts_12wk.csv
        table_counts_before: output/overall_counts_before_12wk.csv
        table_counts_after: output/overall_counts_after_12wk.csv 

  describe_baseline_table_8wk_cohort:
     run: r:latest analysis/baseline_table_8wk.R
     needs: [generate_8wk_cohort]
     outputs:
       moderately_sensitive:
         table_overall: output/blt_overall_8wk.csv   
         table_before: output/blt_before_8wk.csv 
         table_after: output/blt_after_8wk.csv 
         table_overall_counts: output/overall_counts_8wk.csv
         table_counts_before: output/overall_counts_before_8wk.csv
         table_counts_after: output/overall_counts_after_8wk.csv 

  describe_baseline_table_6wk_cohort:
    run: r:latest analysis/baseline_table_6wk.R
    needs: [generate_6wk_cohort]
    outputs:
      moderately_sensitive:
        table_overall: output/blt_overall_6wk.csv   
        table_before: output/blt_before_6wk.csv 
        table_after: output/blt_after_6wk.csv 
        table_overall_counts: output/overall_counts_6wk.csv
        table_counts_before: output/overall_counts_before_6wk.csv
        table_counts_after: output/overall_counts_after_6wk.csv 

##########################
###### ITS analyses ######
##########################

  # describe_ITS_plot_overall:
  #   run: r:latest analysis/pn_check_ITS_plot.R
  #   needs: [generate_8wk_cohort, generate_measures_8wk]
  #   outputs:
  #     moderately_sensitive:
  #       plot_ITS_overall: output/pn_check_ITS_overall_8wk.jpeg 

  # describe_ITS_plot_overall_new:
  #   run: r:latest analysis/pn_check_ITS_plot_new.R
  #   needs: [generate_8wk_cohort, generate_measures_8wk]
  #   outputs:
  #     moderately_sensitive:
  #       plot_ITS_overall: output/pn_check_ITS_overall_8wk_new.jpeg

  ## ITS plot with modelled rates using 8 week cohort 
  describe_ITS_plot_overall_new_modelled:
    run: r:latest analysis/pn_check_ITS_plot_new_plottingmodelledrate.R
    needs: [generate_8wk_cohort, generate_measures_8wk]
    outputs:
      moderately_sensitive:
        plot_ITS_overall: output/pn_check_ITS_overall_8wk_new_modelled.jpeg
        estimates: output/ITS_estimates_overall.csv
        plot_ITS_plot_data: output/ITS_plot_data_overall.csv
        estimates_c: output/ITS_estimates_counter_overall.csv
        combined: output/ITS_estimates_combined_plot_8wk.csv

  describe_ITS_plot_overall_6wk_new:
    run: r:latest analysis/pn_check_ITS_plot_6wk_new.R
    needs: [generate_6wk_cohort, generate_measures_6wk]
    outputs:
      moderately_sensitive:
        plot_ITS_overall_6wk: output/pn_check_ITS_overall_6wk_new_modelled.jpeg 
        estimates: output/ITS_estimates_overall_6wk.csv
        estimates_c: output/ITS_estimates_counter_6wk.csv
        combined: output/ITS_estimates_combined_plot_6wk.csv

  describe_ITS_plot_overall_12wk_new:
    run: r:latest analysis/pn_check_ITS_plot_12wk_new.R
    needs: [generate_12wk_cohort, generate_measures_12wk]
    outputs:
      moderately_sensitive:
        plot_ITS_overall_12wk: output/pn_check_ITS_overall_12wk_new_modelled.jpeg 
        estimates: output/ITS_estimates_overall_12wk.csv
        estimates_c: output/ITS_estimates_counter_12wk.csv
        combined: output/ITS_estimates_combined_plot_12wk.csv

  describe_ITS_plot_overall_by_cohort:
    run: r:latest analysis/pn_check_ITS_plot_combined.R
    needs: [generate_12wk_cohort, generate_measures_12wk, generate_6wk_cohort, generate_measures_6wk, generate_8wk_cohort, generate_measures_8wk]
    # check needs
    outputs:
      moderately_sensitive:
        plot_ITS_overall_by_cohort: output/plot_ITS_overall_by_cohort.jpeg 

  # describe_ITS_plot_age_cat:
  #    run: r:latest analysis/pn_check_ITS_plot_age_cat_vp.R
  #    needs: [generate_8wk_cohort, generate_measures_8wk]
  #    outputs:
  #      moderately_sensitive:
  #         plot_ITS_age_cat: output/plot_ITS_age_cat.jpeg
  #         plot_ITS_age_cat_data: output/plot_ITS_check_age_cat.csv
  #         plot_ITS_IRR_age_cat: output/plot_ITS_age_cat_IRR.jpeg
  #         plot_ITS_IRR_age_cat_data: output/ITS_plot_age_cat_IRR_overall.csv

  describe_ITS_plot_age_cat_edit:
     run: r:latest analysis/pn_check_ITS_plot_age_cat_edit.R
     needs: [generate_8wk_cohort, generate_measures_8wk]
     outputs:
       moderately_sensitive:
          plot_ITS_age_cat_edit: output/plot_ITS_age_cat_edit.jpeg
          plot_ITS_age_cat_data: output/plot_ITS_check_age_cat.csv
          #plot_ITS_age_cat_edit_2: output/plot_ITS_age_cat_edit_2.jpeg
          plot_ITS_IRR_age_cat_data: output/ITS_plot_age_cat_IRR_overall.csv
          plot_ITS_plot_data: output/ITS_plot_data_age_cat.csv

  describe_ITS_plot_ethnicity:
     run: r:latest analysis/pn_check_ITS_plot_ethnicity_new.R
     needs: [generate_8wk_cohort, generate_measures_8wk]
     outputs:
       moderately_sensitive:
          plot_ITS_eth_1: output/plot_ITS_eth_1.jpeg
          plot_ITS_eth_2: output/plot_ITS_eth_2.jpeg
          plot_ITS_eth_data: output/plot_ITS_check_ethnicity.csv
          plot_ITS_IRR_eth_data: output/ITS_plot_ethnicity_IRR_overall.csv
          plot_ITS_plot_data: output/ITS_plot_data_ethnicity.csv

  describe_ITS_plot_imd_new:
     run: r:latest analysis/pn_check_ITS_plot_imd_new.R
     needs: [generate_8wk_cohort, generate_measures_8wk]
     outputs:
       moderately_sensitive:
          plot_ITS_imd_1: output/plot_ITS_imd_1.jpeg
          plot_ITS_imd_2: output/plot_ITS_imd_2.jpeg
          plot_ITS_imd_data: output/plot_ITS_check_imd.csv
          plot_ITS_IRR_imd_data: output/ITS_plot_imd_IRR_overall.csv 
          plot_ITS_plot_data: output/ITS_plot_data_imd.csv

  # describe_ITS_plot_practice:
  #  run: r:latest analysis/pn_check_ITS_plot_practice.R
  #   needs: [generate_8wk_cohort, generate_measures_8wk]
  #   outputs:
  #     moderately_sensitive:
  #        plot_ITS_practice_1: output/plot_ITS_practice_1.jpeg
  #        plot_ITS_practice_2: output/plot_ITS_practice_2.jpeg

  describe_ITS_plot_region:
     run: r:latest analysis/pn_check_ITS_plot_region_new.R
     needs: [generate_8wk_cohort, generate_measures_8wk]
     outputs:
      moderately_sensitive:
         plot_ITS_region_1: output/plot_ITS_region_1.jpeg
         plot_ITS_region_2: output/plot_ITS_region_2.jpeg
         plot_ITS_region_data: output/plot_ITS_check_region.csv
         plot_ITS_IRR_region_data: output/ITS_plot_region_IRR_overall.csv
         plot_ITS_plot_data: output/ITS_plot_data_region.csv

  describe_glm_for_no_pn_check:
      run: r:latest analysis/glm_for_no_pn_check.r
      needs: [generate_8wk_cohort]
      outputs:
       moderately_sensitive:
          mod1_age_coef: output/mod1_ageadj_coef.csv
          #mod1_capture: output/mod1_ageadj_capture.csv
          mod2_full_coef: output/mod2_fulladj_coef.csv
          #mod2_full_capture: output/mod2_fulladj_capture.csv
          mod2_covid_full_coef: output/mod2_covid_fulladj_coef.csv
          mod1_age_OR_CIs: output/mod1_tidy_OR_CI.csv
          mod2_full_OR_CIs: output/mod2_tidy_OR_CI.csv
          mod2_full_covid_OR_CIs: output/mod2_covid_tidy_OR_CI.csv
          mod3_sens_first_OR_CIs: output/mod3_first_OR_CI.csv
          mod3_sens_last_OR_CIs: output/mod3_last_OR_CI.csv
          #forestplot_2: output/glm_fullAdjs.jpeg
          
 

