version: '3.0'

expectations:
  population_size: 1000

actions:

  # this is for number of matches
  # should delivery codes be in population?
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition 
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  #this is to generate a date file for each month
  generate_study_population_monthly:
    run: cohortextractor:latest generate_cohort 
      --study-definition study_definition_monthly 
      --index-date-range "2019-01-01 to today by month"
      --output-dir=output 
      --output-format csv.gz 
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv.gz

  # this is to run measures
  # need to add first/last day of month to variables in study def?
  generate_study_population_measures:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures --index-date-range "2019-01-01 to today by month" --skip-existing --output-dir=output/measures --output-format=csv.gz 
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_measures --skip-existing --output-dir=output/measures
    needs: [generate_study_population_measures]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv

  describe:
    run: r:latest analysis/del_code_histogram.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        cohort: output/del_code_frequency.png


 
